Add page type selection for maintenance mode and update HTML content based on selection

diff --git a/.github/workflows/prod-setup-maintenance-page.yml b/.github/workflows/prod-setup-maintenance-page.yml
--- a/.github/workflows/prod-setup-maintenance-page.yml
+++ b/.github/workflows/prod-setup-maintenance-page.yml
@@ -12,6 +12,14 @@ on:
           - enable
           - disable
 
+      page_type:
+        description: "Select maintenance page type"
+        required: true
+        type: choice
+        options:
+          - provider
+          - maintenance
+
 env:
   AWS_REGION: eu-west-2
   LISTENER_ARN: ${{ secrets.LISTENER_ARN }}
@@ -57,13 +65,28 @@ jobs:
       - name: Enable maintenance
         if: ${{ github.event.inputs.action == 'enable' }}
         run: |
-          HTML='<html><head><title>System Status</title></head><body style="font-family:Arial;text-align:center;padding-top:50px;background:#f5f5f5;"><div style="background:#fff;border-radius:12px;padding:40px;display:inline-block;"><h2 style="color:#e60023;">We are currently down</h2><p>We’re temporarily offline. One of our service providers is currently experiencing technical difficulties, which is affecting SAS.</p><p>We are monitoring the situation closely and will be back online as soon as they resolve the issue.</p><p style="text-align:center;"><b>Thanks for your patience!</b></p></div></body></html>'
+         set -e
+
+          if [[ "${{ github.event.inputs.page_type }}" == "provider" ]]; then
+            echo "Using provider issue page..."
+
+            HTML='<html><head><title>System Status</title></head><body style="font-family:Arial;text-align:center;padding-top:50px;background:#f5f5f5;"><div style="background:#fff;border-radius:12px;padding:40px;display:inline-block;"><h2 style="color:#e60023;">We are currently down</h2><p>We’re temporarily offline. One of our service providers is currently experiencing technical difficulties, which is affecting SAS.</p><p>We are monitoring the situation closely and will be back online as soon as they resolve the issue.</p><p style="text-align:center;"><b>Thanks for your patience!</b></p></div></body></html>'
+
+          elif [[ "${{ github.event.inputs.page_type }}" == "maintenance" ]]; then
+            echo "Using scheduled maintenance page..."
+
+            HTML='<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Service under maintenance</title><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="3"></head><style>html{font-size:62.5%}body,html{height:100%;margin:0;padding:0}body{font-size:1.6em;line-height:2em;font-family:sans-serif;display:flex;flex-direction:column;text-align:center}#wrap{margin:3em}</style><body><div id="wrap"><h2>Sorry for the inconvenience! We’re currently undergoing scheduled maintenance to improve your experience.<br>We’ll be back online shortly. Thank you for your patience!</h2><p style="text-align:right">Sincerely,<br>SellerAmp SAS Team</p><div></body></html>'
+
+          else
+            echo "Invalid page_type"
+          exit 1
+          fi
 
           aws elbv2 modify-listener \
-            --listener-arn "$LISTENER_ARN" \
-            --default-actions "Type=fixed-response,FixedResponseConfig={StatusCode=503,ContentType=text/html,MessageBody='$HTML'}"
+          --listener-arn "$LISTENER_ARN" \
+          --default-actions "Type=fixed-response,FixedResponseConfig={StatusCode=503,ContentType=text/html,MessageBody='$HTML'}"
 
-          echo "✅ Maintenance ENABLED"
+          echo "✅ Maintenance ENABLED with ${{ github.event.inputs.page_type }} page"
 
       - name: Disable maintenance
         if: ${{ github.event.inputs.action == 'disable' }}
